### ISSUE TITLE
Incorrect type declarations on documented methods

### ISSUE THREAD

**Issue by shadowhand** [Respect/Assertion#1]
A lot of the methods declared [in `Assert`][1] are defined as `iterable` when they actually take `mixed`, which causes static analysis errors.

[1]: https://github.com/Respect/Assertion/blob/09c3d915f1aaa9e0b16fa48f0a06f0c734763d92/src/Assert.php#L32-L267

**Comment by henriquemoody** [comment]
As I said before, I completely didn't see this issue before, but this is now fixed on version 0.3.2.

Thanks for reporting and making a pull request! 🐼
